'use client';

import { useState } from 'react';
import {
  Key,
  RefreshCcw,
  Lock,
  ExternalLink,
  Clipboard,
  Terminal,
  FileText,
  ArrowRight,
  ShieldCheck,
  Loader2,
  AlertCircle,
} from 'lucide-react';
import { affiliateApi } from '../../../../services/affiliateApi';
import { useAffiliateData } from '../../../../hooks/useAffiliateData';
import { DataState } from '../../../../components/ui/DataState';
import { confirmDialog, revealOnce, toast } from '../../../../lib/toast';
import { fmtDate, label as humanize } from '../../../../lib/format';

const API_DOCS_URL = 'https://docs.dollara.com/affiliate-integration';

function downloadBlob(filename, text) {
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

/**
 * Partner API credentials.
 *
 * Everything here was previously fabricated in the browser: `buildKeyPair`
 * assembled a PEM-shaped string out of `Date.now()` and `Math.random()`, rotate
 * produced another one, and revoke flipped a local flag. None of it existed
 * server-side, so a partner who wired an integration against it would have been
 * rejected by the very first signed request.
 *
 * Keys are now generated by the API with real RSA. The private half comes back
 * exactly once, in the creation response, and is never stored anywhere — which
 * is why it is force-downloaded behind a confirm the user cannot dismiss by
 * clicking outside.
 */
export default function SettingsApiPage() {
  const [busy, setBusy] = useState(false);
  const [webhookUrl, setWebhookUrl] = useState('');
  const [webhookDirty, setWebhookDirty] = useState(false);
  const [webhookSaved, setWebhookSaved] = useState(false);
  const [webhookError, setWebhookError] = useState('');

  const keysQuery = useAffiliateData('/api/v1/affiliate/api-keys', []);
  const configQuery = useAffiliateData('/api/v1/affiliate/webhook-config', []);
  const logsQuery = useAffiliateData('/api/v1/affiliate/api-logs?limit=20', []);

  const keys = keysQuery.data?.records ?? [];
  const config = configQuery.data;
  const logs = logsQuery.data?.records ?? [];

  // The most recent usable key drives the panel; revoked ones stay listed below.
  const apiKey = keys.find((k) => k.status !== 'revoked') ?? keys[0] ?? null;

  const effectiveWebhook = webhookDirty ? webhookUrl : (config?.webhook_url ?? '');

  /** Show the private key once, then push it to disk. */
  const revealPrivateKey = async (payload) => {
    await revealOnce({
      title: 'Save your private key now',
      html: `
        <p style="font-size:13px;text-align:left;margin-bottom:10px">
          This is the only time this key is shown. It is not stored on our side and
          cannot be recovered — if you lose it you will have to rotate.
        </p>
        <textarea readonly rows="8" style="width:100%;font-family:monospace;font-size:10px;padding:8px;border-radius:8px;border:1px solid #334155;background:#0f172a;color:#e2e8f0">${payload.private_pem}</textarea>
      `,
      confirmText: 'I have saved it',
    });
    downloadBlob(`${payload.key_id}-private-key.pem`, payload.private_pem);
  };

  const handleGenerateKey = async () => {
    if (busy) return;
    setBusy(true);
    try {
      const created = await affiliateApi('/api/v1/affiliate/api-keys', { method: 'POST' });
      await revealPrivateKey(created);
      toast.success('API keypair generated');
      keysQuery.reload();
    } catch (err) {
      toast.error(err.message);
    } finally {
      setBusy(false);
    }
  };

  const handleRotateKey = async () => {
    if (!apiKey || busy) return;
    const ok = await confirmDialog({
      title: 'Rotate this key?',
      text: 'A new keypair is issued immediately. The old key keeps working for a '
        + '24-hour grace window so your in-flight requests do not break.',
      confirmText: 'Rotate key',
    });
    if (!ok) return;

    setBusy(true);
    try {
      const rotated = await affiliateApi(
        `/api/v1/affiliate/api-keys/${apiKey.id}/rotate`,
        { method: 'POST' },
      );
      await revealPrivateKey(rotated);
      toast.success('Key rotated — the previous key expires in 24 hours');
      keysQuery.reload();
    } catch (err) {
      toast.error(err.message);
    } finally {
      setBusy(false);
    }
  };

  const handleRevokeKey = async () => {
    if (!apiKey || busy) return;
    const ok = await confirmDialog({
      title: 'Revoke this key immediately?',
      text: 'Any integration signing with it stops working on the next request. '
        + 'There is no grace period.',
      confirmText: 'Revoke key',
      danger: true,
    });
    if (!ok) return;

    setBusy(true);
    try {
      await affiliateApi(`/api/v1/affiliate/api-keys/${apiKey.id}/revoke`, {
        method: 'POST',
      });
      toast.success('Key revoked');
      keysQuery.reload();
    } catch (err) {
      toast.error(err.message);
    } finally {
      setBusy(false);
    }
  };

  const handleSaveWebhook = async () => {
    setWebhookError('');
    try {
      await affiliateApi('/api/v1/affiliate/webhook-config', {
        method: 'PUT',
        body: JSON.stringify({ webhookUrl: effectiveWebhook }),
      });
      setWebhookSaved(true);
      setWebhookDirty(false);
      configQuery.reload();
      window.setTimeout(() => setWebhookSaved(false), 2200);
    } catch (err) {
      // The API rejects non-HTTPS URLs; say so rather than flashing "Saved".
      setWebhookError(err.message || 'Could not save that URL.');
    }
  };

  const statusClasses = {
    active: 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-300 border-emerald-500/20',
    rotating: 'bg-sky-500/10 text-sky-600 dark:text-sky-300 border-sky-500/20',
    revoked: 'bg-rose-500/10 text-rose-600 dark:text-rose-300 border-rose-500/20',
  };

  return (
    <div className="space-y-6 animate-fade-up">

      {/* page header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-xl sm:text-2xl font-black font-display tracking-tight text-slate-900 dark:text-slate-100">
            API & Integration
          </h1>
          <p className="text-xs sm:text-sm text-slate-500 dark:text-slate-400 mt-1">
            Generate signed API credentials, configure your webhook endpoint, and review recent signed call activity.
          </p>
        </div>

        <a
          href={API_DOCS_URL}
          target="_blank"
          rel="noreferrer"
          className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950/80 text-slate-700 dark:text-slate-200 text-sm font-semibold hover:bg-slate-100 dark:hover:bg-slate-900 transition-all"
        >
          <ExternalLink className="w-4 h-4" /> View API docs
        </a>
      </div>


      <div className="grid gap-4 xl:grid-cols-[1.7fr_1fr]">

        {/* left column */}
        <div className="space-y-4">

          {/* keypair section */}
          <section className="rounded-3xl bg-white dark:bg-slate-900 border border-slate-200/70 dark:border-slate-800/80 p-5 shadow-sm">
            <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between">
              <div>
                <h2 className="text-sm font-semibold uppercase tracking-[0.24em] text-slate-500 dark:text-slate-400">
                  API keypair
                </h2>
                <p className="mt-2 text-xs text-slate-500 dark:text-slate-400">
                  Generate a keypair for signed webhook calls and API access. The private key is shown only once.
                </p>
              </div>

              <div className="flex flex-wrap gap-2">
                {!apiKey && (
                  <button
                    type="button"
                    onClick={handleGenerateKey}
                    disabled={busy}
                    className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-gradient-to-r from-brand-400 to-brand-600 text-black font-bold text-sm shadow-sm hover:shadow-md hover:brightness-105 transition-all disabled:opacity-60"
                  >
                    {busy ? <Loader2 className="w-4 h-4 animate-spin" /> : <Key className="w-4 h-4" />}
                    Generate keypair
                  </button>
                )}

                {apiKey && apiKey.status !== 'revoked' && (
                  <>
                    <button
                      type="button"
                      onClick={handleRotateKey}
                      disabled={busy}
                      className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl disabled:opacity-60 border border-slate-200 dark:border-slate-800 text-slate-700 dark:text-slate-200 bg-slate-100 dark:bg-slate-950/80 text-sm font-semibold hover:bg-slate-200 dark:hover:bg-slate-900 transition-all"
                    >
                      <RefreshCcw className="w-4 h-4" /> Rotate key
                    </button>

                    <button
                      type="button"
                      onClick={handleRevokeKey}
                      disabled={busy}
                      className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl disabled:opacity-60 border border-rose-300 bg-rose-500/10 text-rose-500 text-sm font-semibold hover:bg-rose-500/20 transition-all"
                    >
                      <Lock className="w-4 h-4" /> Revoke key
                    </button>
                  </>
                )}

                {apiKey?.status === 'revoked' && (
                  <button
                    type="button"
                    onClick={handleGenerateKey}
                    disabled={busy}
                    className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-gradient-to-r from-brand-400 to-brand-600 text-black font-bold text-sm shadow-sm hover:shadow-md hover:brightness-105 transition-all disabled:opacity-60"
                  >
                    <Key className="w-4 h-4" /> Generate new key
                  </button>
                )}
              </div>
            </div>

            {apiKey ? (
              <div className="mt-6 space-y-4">
                <div className="flex flex-wrap items-center gap-3 text-sm">
                  <span
                    className={`inline-flex items-center rounded-full border px-3 py-1 text-xs font-semibold ${statusClasses[apiKey.status]}`}
                  >
                    {apiKey.status}
                  </span>
                  <span className="font-mono text-xs text-slate-500 dark:text-slate-400">
                    {apiKey.key_id}
                  </span>
                  <span className="text-xs text-slate-500 dark:text-slate-400">
                    Created: {fmtDate(apiKey.created_at)}
                  </span>
                  {apiKey.grace_until && (
                    <span className="text-xs text-amber-600 dark:text-amber-400">
                      Expires: {fmtDate(apiKey.grace_until)}
                    </span>
                  )}
                  {apiKey.last_used_at && (
                    <span className="text-xs text-slate-500 dark:text-slate-400">
                      Last used: {fmtDate(apiKey.last_used_at)}
                    </span>
                  )}
                </div>

                {/* public key */}
                <div className="space-y-3">
                  <label className="block text-xs font-semibold uppercase tracking-[0.24em] text-slate-500 dark:text-slate-400">
                    Public key
                  </label>
                  <textarea
                    readOnly
                    value={apiKey.public_pem}
                    rows={4}
                    className="w-full rounded-3xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950/80 px-4 py-3 text-xs text-slate-800 dark:text-slate-100 font-mono"
                  />
                </div>

                {apiKey.fingerprint && (
                  <p className="font-mono text-[10px] text-slate-400">
                    SHA-256 fingerprint: {apiKey.fingerprint}
                  </p>
                )}

                {/* The private half is only ever in the creation response — it
                    is not stored, so there is nothing to render here. */}
                <div className="rounded-3xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950/80 p-4 text-sm text-slate-600 dark:text-slate-300">
                  The private key was shown once when this key was issued and is not
                  stored on our side. If you no longer have it, rotate the key to get
                  a new pair.
                </div>
              </div>
            ) : (
              <div className="mt-6 rounded-3xl border border-dashed border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950/80 p-6 text-sm text-slate-500 dark:text-slate-400">
                No API credentials have been issued yet. Generate a keypair to start using the affiliate API and signed webhooks.
              </div>
            )}
          </section>


          {/* webhook section */}
          <section className="rounded-3xl bg-white dark:bg-slate-900 border border-slate-200/70 dark:border-slate-800/80 p-5 shadow-sm">
            <div className="flex items-center justify-between gap-4">
              <div>
                <h2 className="text-sm font-semibold uppercase tracking-[0.24em] text-slate-500 dark:text-slate-400">
                  Webhook endpoint
                </h2>
                <p className="mt-2 text-xs text-slate-500 dark:text-slate-400">
                  Configure the endpoint where affiliate webhook events are posted. Use HTTPS and verify the request signatures.
                </p>
              </div>

              <span className="inline-flex items-center gap-2 rounded-full bg-slate-100 dark:bg-slate-950/80 px-3 py-1 text-[11px] font-semibold text-slate-600 dark:text-slate-300">
                <Terminal className="w-3.5 h-3.5" /> Signed webhook
              </span>
            </div>

            <div className="mt-4 space-y-3">
              <input
                type="text"
                value={effectiveWebhook}
                placeholder="https://your-domain.example/webhooks/dollara"
                onChange={(event) => {
                  setWebhookUrl(event.target.value);
                  setWebhookDirty(true);
                }}
                className="w-full rounded-3xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950/80 px-4 py-3 text-sm text-slate-900 dark:text-slate-100 focus:outline-none focus:ring-2 focus:ring-brand-500/20"
              />

              <div className="flex flex-wrap items-center gap-2">
                <button
                  type="button"
                  onClick={handleSaveWebhook}
                  className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-brand-500 text-black text-sm font-semibold hover:bg-brand-600 transition-all"
                >
                  Save webhook URL
                </button>

                {webhookSaved && (
                  <span className="text-xs font-semibold text-emerald-500">Saved</span>
                )}
              </div>

              {webhookError && (
                <div className="flex items-start gap-2 rounded-xl border border-danger-400/40 bg-danger-500/10 px-3 py-2.5 text-xs text-danger-600">
                  <AlertCircle className="mt-0.5 h-3.5 w-3.5 shrink-0" />
                  <span>{webhookError}</span>
                </div>
              )}

              <p className="text-xs text-slate-500 dark:text-slate-400">
                Current webhook URL:{' '}
                <span className="font-semibold text-slate-900 dark:text-slate-100">
                  {config?.webhook_url || 'not configured'}
                </span>
              </p>

              {/* Says plainly what is and is not live, rather than implying
                  events are already being delivered. */}
              <p className="rounded-2xl bg-slate-50 px-3 py-2.5 text-xs text-slate-500 dark:bg-slate-950/60 dark:text-slate-400">
                Inbound signed calls to Dollara are live today. Outbound delivery of
                events to this URL is not enabled yet — the address is stored so it
                is ready when it ships.
              </p>
            </div>
          </section>
        </div>


        {/* right side - checklist */}
        <section className="rounded-3xl bg-white dark:bg-slate-900 border border-slate-200/70 dark:border-slate-800/80 p-5 shadow-sm">
          <div className="flex items-center gap-3 text-slate-500 dark:text-slate-400">
            <ShieldCheck className="w-5 h-5" />
            <span className="text-sm font-semibold">Signed integration checklist</span>
          </div>

          <div className="mt-4 space-y-3 text-sm text-slate-600 dark:text-slate-300">
            <div className="rounded-2xl bg-slate-50 dark:bg-slate-950/60 p-3">
              <div className="font-semibold">Signing headers</div>
              <div className="text-xs mt-1 text-slate-500 dark:text-slate-400">
                Use `X-Aff-Key-Id`, `X-Aff-Timestamp`, `X-Aff-Nonce`, and `X-Aff-Signature`.
              </div>
            </div>

            <div className="rounded-2xl bg-slate-50 dark:bg-slate-950/60 p-3">
              <div className="font-semibold">Webhook delivery</div>
              <div className="text-xs mt-1 text-slate-500 dark:text-slate-400">
                The webhook URL must be HTTPS and verify the returned signature.
              </div>
            </div>

            <div className="rounded-2xl bg-slate-50 dark:bg-slate-950/60 p-3">
              <div className="font-semibold">Request log</div>
              <div className="text-xs mt-1 text-slate-500 dark:text-slate-400">
                Review the last N signed calls below for debugging and validation.
              </div>
            </div>
          </div>

          <div className="mt-6 rounded-3xl border border-slate-200/70 dark:border-slate-800/80 bg-slate-100 dark:bg-slate-950/80 p-4">
            <div className="flex items-center justify-between gap-2 text-sm text-slate-600 dark:text-slate-400">
              <div className="font-semibold text-slate-900 dark:text-slate-100">
                Integration resources
              </div>
              <a
                href={API_DOCS_URL}
                target="_blank"
                rel="noreferrer"
                className="inline-flex items-center gap-1 text-slate-700 dark:text-slate-200"
              >
                Open docs <ArrowRight className="w-4 h-4" />
              </a>
            </div>

            <div className="mt-4 grid gap-3">
              <div className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-4 text-sm">
                <div className="font-semibold">Webhook endpoint</div>
                <div className="mt-1 break-all text-slate-500 dark:text-slate-400">
                  {config?.postback_endpoint || '—'}
                </div>
              </div>

              <div className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-4 text-sm">
                <div className="font-semibold">Signed request example</div>
                <div className="mt-1 text-slate-500 dark:text-slate-400">
                  POST /api/v1/affiliate/webhook/postback
                </div>
              </div>

              <div className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-4 text-sm">
                <div className="font-semibold">Key header</div>
                <div className="mt-1 text-slate-500 dark:text-slate-400">X-Aff-Key-Id</div>
              </div>
            </div>
          </div>
        </section>
      </div>


      {/* request log table */}
      <section className="rounded-3xl bg-white dark:bg-slate-900 border border-slate-200/70 dark:border-slate-800/80 p-5 shadow-sm">
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-4">
          <div>
            <h2 className="text-base font-black font-display text-slate-900 dark:text-slate-100">
              Signed request log
            </h2>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
              The most recent signed webhook and API call activity for debugging.
            </p>
          </div>

          <div className="inline-flex items-center gap-2 rounded-full bg-slate-100 dark:bg-slate-950/80 px-4 py-2 text-xs font-semibold text-slate-600 dark:text-slate-300">
            <FileText className="w-4 h-4" /> Last {logs.length} events
          </div>
        </div>

        <DataState
          loading={logsQuery.loading}
          error={logsQuery.error}
          onRetry={logsQuery.reload}
          empty={!logs.length}
          emptyTitle="No signed calls yet"
          emptyHint="Once your integration signs a request to Dollara it shows up here, valid or not."
          emptyIcon={Terminal}
        >
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse text-xs">
            <thead>
              <tr className="bg-slate-50 dark:bg-slate-950/40 border-b border-slate-200/40 dark:border-slate-800/60 text-slate-500 dark:text-slate-400 font-bold uppercase tracking-wider text-[10px]">
                <th className="p-4">When</th>
                <th className="p-4">Direction</th>
                <th className="p-4">Endpoint</th>
                <th className="p-4">Status</th>
                <th className="p-4">Signature</th>
                <th className="p-4">Note</th>
              </tr>
            </thead>

            <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
              {logs.map((entry) => (
                <tr
                  key={entry.id}
                  className="hover:bg-slate-50/60 dark:hover:bg-slate-800/40 transition-colors"
                >
                  <td className="p-4 whitespace-nowrap text-slate-600 dark:text-slate-300">
                    {fmtDate(entry.created_at)}
                  </td>
                  <td className="p-4 font-semibold capitalize text-slate-900 dark:text-slate-100">
                    {entry.direction}
                  </td>
                  <td className="p-4 font-mono text-[11px] text-slate-600 dark:text-slate-300">
                    {entry.method} {entry.endpoint}
                  </td>
                  <td className="p-4 text-slate-600 dark:text-slate-300">{entry.status_code}</td>
                  <td className="p-4">
                    <span
                      className={`rounded-full px-2 py-0.5 text-[10px] font-bold capitalize ${
                        entry.signature_result === 'valid'
                          ? 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400'
                          : 'bg-rose-500/10 text-rose-600 dark:text-rose-400'
                      }`}
                    >
                      {humanize(entry.signature_result)}
                    </span>
                  </td>
                  <td className="p-4 text-slate-600 dark:text-slate-300">{entry.note || '—'}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        </DataState>
      </section>

    </div>
  );
}