# Generated by Django 5.1.15 on 2026-05-17 05:15

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.CharField(default=core.models.uuid_str, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('finance_manager', 'Finance Manager'), ('support_lead', 'Support Lead'), ('support_agent', 'Support Agent'), ('marketing_manager', 'Marketing Manager'), ('risk_manager', 'Risk Manager'), ('game_manager', 'Game Manager'), ('reporting_analyst', 'Reporting Analyst')], max_length=30)),
                ('two_factor_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_users',
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.CharField(default=core.models.uuid_str, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('display_title', models.CharField(blank=True, max_length=150, null=True)),
                ('bonus_type', models.CharField(max_length=20)),
                ('value_type', models.CharField(max_length=20)),
                ('value_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('max_bonus_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('wagering_multiplier', models.DecimalField(decimal_places=2, default=35, max_digits=5)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bonuses',
            },
        ),
        migrations.CreateModel(
            name='GameProvider',
            fields=[
                ('id', models.CharField(default=core.models.uuid_str, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'game_providers',
            },
        ),
        migrations.CreateModel(
            name='OtpVerification',
            fields=[
                ('id', models.CharField(default=core.models.uuid_str, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('otp_hash', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('voice', 'Voice')], default='sms', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'otp_verifications',
            },
        ),
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('setting_key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('setting_value', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'platform_settings',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=core.models.uuid_str, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(default='IN', max_length=2)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('website_language', models.CharField(default='en', max_length=10)),
                ('communication_language', models.CharField(default='en', max_length=10)),
                ('registration_path', models.CharField(choices=[('otp', 'OTP'), ('kyc', 'KYC')], default='otp', max_length=10)),
                ('kyc_status', models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='none', max_length=20)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('is_demo', models.BooleanField(default=False)),
                ('demo_expires_at', models.DateTimeField(blank=True, null=True)),
                ('ai_voice_executive_id', models.CharField(blank=True, max_length=50, null=True)),
                ('fraud_score', models.IntegerField(default=0)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(default=core.models.uuid_str, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('slots', 'Slots'), ('live_casino', 'Live Casino'), ('sports', 'Sports'), ('lottery', 'Lottery'), ('ai_games', 'AI Games'), ('fantasy', 'Fantasy'), ('virtual_sports', 'Virtual Sports')], max_length=30)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('rtp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_bet', models.DecimalField(decimal_places=2, default=10, max_digits=18)),
                ('max_bet', models.DecimalField(decimal_places=2, default=100000, max_digits=18)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active_web', models.BooleanField(default=True)),
                ('is_provably_fair', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('play_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(db_column='provider_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gameprovider')),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(default=core.models.uuid_str, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('bonus_credit', 'Bonus Credit'), ('bet_settlement', 'Bet Settlement'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.CharField(default=core.models.uuid_str, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('odds', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost'), ('void', 'Void'), ('cancelled', 'Cancelled'), ('cashout', 'Cashout')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(db_column='game_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.game')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'bets',
            },
        ),
        migrations.CreateModel(
            name='AiCallLog',
            fields=[
                ('id', models.CharField(default=core.models.uuid_str, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('voice_executive_id', models.CharField(blank=True, max_length=50, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('deposit_intent', models.BooleanField(default=False)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'ai_call_logs',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.CharField(default=core.models.uuid_str, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('main_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('bonus_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('exposure_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('locked_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalStage',
            fields=[
                ('id', models.CharField(default=core.models.uuid_str, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('stage', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(db_column='transaction_id', on_delete=django.db.models.deletion.CASCADE, to='core.transaction')),
            ],
            options={
                'db_table': 'withdrawal_stages',
            },
        ),
    ]
